<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation Starter Template</title>
    <!-- Compressed CSS -->
    <link
            rel="stylesheet"
            href="/css/foundation.min.css"
    />
    <link rel="stylesheet" href="/css/styles.css" />
</head>
<body>
<!-- Start Top Bar -->
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <a class="menu-text"><a href="<?=$baseUrl?>" Multi level categories</a></li>
            <li class="has-submenu">
                <a href="<?=$baseUrl?>/show-category/1">Electronics</a>
                <ul class="submenu menu vertical" data-submenu>
                    <li><a href="#">Monitors</a></li>
                    <li><a href="#">Tablets</a></li>
                    <li>
                        <a href="#">Computers</a>
                        <ul class="submenu menu vertical" data-submenu>
                            <li><a href="#">Desktops</a></li>
                            <li><a href="#">Notebooks</a></li>
                            <li>
                                <a href="#">Laptops</a>
                                <ul class="submenu menu vertical" data-submenu>
                                    <li><a href="#">Asus</a></li>
                                    <li><a href="#">Dell</a></li>
                                    <li>
                                        <a href="#">Acer</a>
                                        <ul class="submenu menu vertical" data-submenu>
                                            <li><a href="#">FullHD</a></li>
                                            <li><a href="#">HD+</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="#">Videos</a></li>
            <li>
                <a href="#">Software</a>
                <ul class="submenu menu vertical" data-submenu>
                    <li>
                        <a href="#">Operating systems</a>
                        <ul class="submenu menu vertical" data-submenu>
                            <li><a href="#">Linux</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Servers</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Search" /></li>
            <li><button type="button" class="button">Search</button></li>
        </ul>
    </div>
</div>
<!-- End Top Bar -->
<br />
<br />
