<?php include('layout/header.phtml');?>
<div class="grid-container">
    <div class="grid-x grid-margin-x">
        <div class="medium-6 cell">
            <h3>
                <?php if ($editCategory ?? false): ?>
                Edit category
                <?php else: ?>
                Add a new category
                <?php endif;?>
            </h3>
<!--            <div class="callout success">-->
<!--                Category was saved-->
<!--            </div>-->
<!--            <div class="callout alert">-->
<!--                Fill correctly the form-->
<!--            </div>-->
            <?php if($category_delete ?? false): ?>
            <div class="callout alert">
                Category was deleted
            </div>
            <?php endif; ?>
            <label
            >Name
                <input type="text" placeholder="Name" value="<?=$editCategory['name'] ?? null?>"/>
            </label>
            <label
            >Description
                <textarea placeholder="Description"></textarea>
            </label>
            <label
            >Parent category
                <select>
                    <option>--choose--</option>
                    <option value="">Electronics</option>
                    <option value="">&nbsp;&nbsp;Monitors</option>
                    <option value="">&nbsp;&nbsp;Tablets</option>
                    <option value="">&nbsp;&nbsp;Computers</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Desktops</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Notebooks</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Laptops</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asus</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dell</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acer</option>
                    <option value=""
                    >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FullHD</option
                    >
                    <option value=""
                    >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HD+</option
                    >
                    <option value="">Videos</option>
                    <option value="">Software</option>
                    <option value="">&nbsp;&nbsp;Operating systems</option>
                    <option value="">&nbsp;&nbsp;&nbsp;&nbsp;Linux</option>
                    <option value="">&nbsp;&nbsp;Servers</option>
                </select>
            </label>
            <input
                    type="submit"
                    class="button expanded"
                    value="Save category"
            />
        </div>

        <div class="medium-6 large-5 cell large-offset-1">
            <div class="basic-card">
                <div class="basic-card-content content callout secondary">
                    <h5><?=$category ?? 'Choose a category form the menu'  ?></h5>
                    <?php if ($category ?? false): ?>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi
                        saepe, asperiores dolor nesciunt dolore, accusamus minus
                        repellendus vero odio, quibusdam, ipsum nisi in a molestiae ex
                        assumenda nulla eveniet eos!
                    </p>
                    <?php endif; ?>
                </div>
                <?php if ($category ?? false): ?>
                <div class="links callout primary">
                    <ul class="menu">
                        <li>
                            <a href="<?=$baseUrl?>/edit-category/1">Edit</a>
                        </li>
                        <li>
                            <a id="delete-category-confirmation" onclick="return confirm('Are your sure?')"
                               href="<?=$baseUrl?>/delete-category/1">Delete</a>
                        </li>
                    </ul>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <hr />
</div>
<?php include('layout/footer.phtml');?>